FROM registry.access.redhat.com/rhel
MAINTAINER Pavel Odvody <podvody@redhat.com>

ENV PACKAGES='http://download.devel.redhat.com/brewroot/packages/which/2.20/7.el7/x86_64/which-2.20-7.el7.x86_64.rpm  http://download.devel.redhat.com/brewroot/packages/python-backports/1.0/8.el7/x86_64/python-backports-1.0-8.el7.x86_64.rpm http://download.devel.redhat.com/brewroot/packages/python-backports-ssl_match_hostname/3.4.0.2/4.el7/noarch/python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch.rpm http://download.devel.redhat.com/brewroot/packages/python-setuptools/0.9.8/4.el7/noarch/python-setuptools-0.9.8-4.el7.noarch.rpm http://download.devel.redhat.com/brewroot/packages/tar/1.26/29.el7/x86_64/tar-1.26-29.el7.x86_64.rpm'

RUN rpm -Uvh ${PACKAGES}\
 && curl -sSL https://github.com/pyinstaller/pyinstaller/releases/download/3.0/PyInstaller-3.0.tar.gz | tar zxvf -\
 && useradd pyinstaller

ENTRYPOINT ["/bin/bash"]
